### ISSUE TITLE
Unit tests fail

### ISSUE THREAD

**Issue by sptrakesh** [gt-health/GT-FHIR#107]
The following test failures happen (building off master branch)

```09:39:50.907 [main] INFO  ca.uhn.fhir.context.FhirContext - Creating new FHIR context for FHIR version [DSTU2]
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.981 sec <<< FAILURE! - in edu.gatech.i3l.fhir.jpa.dao.BaseFhirDaoTest
testTranslateMatchUrl(edu.gatech.i3l.fhir.jpa.dao.BaseFhirDaoTest)  Time elapsed: 0.655 sec  <<< ERROR!
ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: Failed to parse match URL[Condition?subject=304&_lastUpdated=>2011-01-01T11:12:21.0000Z] - Resource type Condition does not have a parameter with name: subject
	at edu.gatech.i3l.fhir.jpa.dao.BaseFhirDaoTest.testTranslateMatchUrl(BaseFhirDaoTest.java:16)```


```09:39:54.863 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Initialized JPA EntityManagerFactory for persistence unit 'GT_FHIR_UT'
09:39:54.872 [main] INFO  ca.uhn.fhir.context.FhirContext - Creating new FHIR context for FHIR version [DSTU2]
09:39:54.915 [main] WARN  o.s.c.s.ClassPathXmlApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'myBaseDao': Unsatisfied dependency expressed through field 'myResourceDaos'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.List<edu.gatech.i3l.fhir.jpa.dao.IFhirResourceDao<?>>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
09:39:54.915 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'GT_FHIR_UT'
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 3.313 sec <<< FAILURE! - in edu.gatech.i3l.fhir.jpa.provider.ResourceProviderDstu2Test
edu.gatech.i3l.fhir.jpa.provider.ResourceProviderDstu2Test  Time elapsed: 3.313 sec  <<< ERROR!
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'myBaseDao': Unsatisfied dependency expressed through field 'myResourceDaos'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.List<edu.gatech.i3l.fhir.jpa.dao.IFhirResourceDao<?>>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at edu.gatech.i3l.fhir.jpa.provider.ResourceProviderDstu2Test.beforeClass(ResourceProviderDstu2Test.java:1556)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.List<edu.gatech.i3l.fhir.jpa.dao.IFhirResourceDao<?>>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at edu.gatech.i3l.fhir.jpa.provider.ResourceProviderDstu2Test.beforeClass(ResourceProviderDstu2Test.java:1556)

edu.gatech.i3l.fhir.jpa.provider.ResourceProviderDstu2Test  Time elapsed: 3.313 sec  <<< ERROR!
java.lang.NullPointerException
	at edu.gatech.i3l.fhir.jpa.provider.ResourceProviderDstu2Test.afterClass(ResourceProviderDstu2Test.java:1541)

Running edu.gatech.i3l.fhir.jpa.testutil.SpringFileTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE! - in edu.gatech.i3l.fhir.jpa.testutil.SpringFileTest
testNoBadResources(edu.gatech.i3l.fhir.jpa.testutil.SpringFileTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NullPointerException
	at edu.gatech.i3l.fhir.jpa.testutil.SpringFileTest.testNoBadResources(SpringFileTest.java:13)


Results :

Tests in error: 
  BaseFhirDaoTest.testTranslateMatchUrl:16 » InvalidRequest Failed to parse matc...
edu.gatech.i3l.fhir.jpa.provider.ResourceProviderDstu2Test.edu.gatech.i3l.fhir.jpa.provider.ResourceProviderDstu2Test
  Run 1: ResourceProviderDstu2Test.beforeClass:1556 » UnsatisfiedDependency Error creat...
  Run 2: ResourceProviderDstu2Test.afterClass:1541 NullPointer

  SpringFileTest.testNoBadResources:13 » NullPointer

Tests run: 3, Failures: 0, Errors: 3, Skipped: 0

[ERROR] There are test failures.```

**Comment by myungchoi** [comment]
Test fails. We couldn't complete the testing units. When you build, please skip test.
